/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:49766311-756c-4c0b-a77e-7da0eca62f76",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_9SuXSQh2L",
    "aws_user_pools_web_client_id": "4q2tng75ticicfla9m5k6se8dl",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://fosv45i2o5cahd75kmmjqphsne.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4k7jli2lmjgqbphcakegxskqhe",
    "aws_user_files_s3_bucket": "amplifyapp99aeba691caa425db7d04ed8a24a8e3e140546-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
